######################## default configuration ####################
baseURL = ""
title = "Hugo documentation theme"
theme = "godocs-1"
# google analytics
googleAnalytics = "" # example : UA-123-45
# disable language
disableLanguages = [] # desable language from here

# hugo outputs
[outputs]
home = ["HTML", "JSON"]

# render unsafe html
[markup.goldmark.renderer]
unsafe = true

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/search/auto-complete.css"
[[params.plugins.css]]
link = "plugins/featherlight/featherlight.min.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/js/all.min.js"
attributes = "crossorigin='anonymous' defer='defer' data-search-pseudo-elements"
[[params.plugins.js]]
link = "plugins/masonry/masonry.min.js"
[[params.plugins.js]]
link = "plugins/featherlight/featherlight.min.js"
[[params.plugins.js]]
link = "plugins/clipboard/clipboard.min.js"
[[params.plugins.js]]
link = "plugins/search/auto-complete.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[[params.plugins.js]]
link = "plugins/search/lunr.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search-page.js"

# site variables
[params.variables]
# Color Variables
primary_color = "#FF0043"
text_color = "#333"
text_color_dark = "#222"
text_color_light = "#999"
body_color = "#fff"
border_color = "#E2E2E2"
black = "#000"
white = "#fff"
light = "#FBFBFB"

# Font Variables
primary_font = "Montserrat:wght@300;400;500;600;700;800"
primary_font_type = "sans-serif"                         # [serif/sans-serif]
secondary_font = ""
secondary_font_type = ""                                 # [serif/sans-serif]
icon_font = "Font Awesome 5 Free"

#################### default parameters ################################
[params]
logo = "images/logo.png"
favicon = "images/favicon.png"
# Meta data
description = "This is meta description"
author = "Themefisher"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io

# Preloader
[params.preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.


############################# social site ########################



################################### English language #####################################
[Languages.en]
languageName = "En"
languageCode = "en-us"
weight = 1
# copyright
copyright = "Neeldhara Misra ⸱ Creative Commons <a href=\"https://creativecommons.org/licenses/by/4.0/\">Attribution 4.0 International (CC BY 4.0)</a>"



# banner
[Languages.en.banner]
title = "Courses"
subtitle = "This website documents the courses I have taught or been involved in coordinating over the years. <br> <br> <a href=\"www.google.com\">IITGN</a> ⸱ NPTEL ⸱ Short Courses ⸱ Other"

############## English navigation ###############
# main menu


# footer menu