project:
  type: website
  output-dir: _site
  preview:
    port: 7770

website:
  title: "Courses"
  navbar:
    pinned: true
    background: white
    left:
      - text: "IITGN"
        href: iitgn.qmd
      - text: "Online"
        href: online.qmd
      - text: "Short Courses"
        href: short.qmd
      - text: "Other"
        href: other.qmd
    right:
      - icon: youtube
        href: https://www.youtube.com/@neeldhara
      - icon: github
        href: https://github.com/neeldhara
      - icon: twitter
        href: https://twitter.com/neeldhara
      - icon: mastodon
        href: https://mathstodon.xyz/@neeldhara
      - text: "{{< fa brands bluesky >}}"
        href: https://bsky.app/profile/neeldhara.bsky.social
      - icon: instagram
        href: http://instagram.com/neeldharamisra
      - icon: globe
        href: https://www.neeldhara.com
      - icon: rss
        href: index.xml
  page-footer:
    left: |
      Made with [Quarto](https://quarto.org) and 🩶
    right: |
      Content {{< fa brands creative-commons >}} {{< fa brands creative-commons-by >}} by [Neeldhara Misra](https://www.neeldhara.com)
  cookie-consent: false
  page-navigation: true

format:
  html:
    theme: cosmo
    css: styles.css
    js: scripts.js
    toc: true
    page-layout: full
    include-in-header:
      - text: |
          <link rel="preconnect" href="https://fonts.googleapis.com">
          <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
          <link href="https://fonts.googleapis.com/css2?family=Berkshire+Swash&family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100;1,300;1,400;1,700;1,900&display=swap" rel="stylesheet">
          <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
          <script>
          window.addEventListener('load', function() {
            var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]')); 
            tooltipTriggerList.forEach(function(element) {
              new bootstrap.Tooltip(element, {
                trigger: 'hover',
                animation: true,
                delay: { show: 50, hide: 50 }
              });
            });
          });
          </script>

filters:
  - fontawesome
